correcting azure app service recommendations
aquasecurity/tfsec pull request #1091
Opened 2021-09-28 08:02 UTC by leesutcliffe

This PR is to fix three issue within the `azurerm_app_service` resource

- detailed_error_messages_enabled
- ftps_state
- http_logs

### detailed_error_messages_enabled
`detailed_error_messages_enabled` should be moved within the `logs` child resource block as documented https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#detailed_error_messages_enabled

### ftps_state
`ftps_state` should be moved to the `site_config` child resource block as documented 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#ftps_state

### http_logs
'http_logs' should be contain a `file_system` or `azure_blob_storage` child resource block. For simplicity, the purpose of the 'Good Example' code refers only to `file_system`. Additionally, the examples values for `retention_in_days` and `retention_in_mb` have been modified to values acceptable by Terraform
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#file_system

2021-09-29 18:51 UTC, owenrumney requested changes
This is great, thanks @leesutcliffe  - just one question, it might not be correct so just say

2021-09-29 18:51 UTC, owenrumney commented on internal/app/tfsec/rules/azure/appservice/http_logs_enabled_rule.go
> +			if logProps.MissingNestedChild("http_logs.file_system") {
Should this be a check for both types of http_logs? I guess the description would need changing too if you agree
```suggestion
			if logProps.MissingNestedChild("http_logs.file_system") && logProps.MissingNestedChild("http_logs.azure_blob_storage") {
```

2021-09-30 13:49 UTC, leesutcliffe commented
Thanks for the suggestion, @owenrumney I have added two good examples and updated the logic.

2021-09-30 19:12 UTC, owenrumney approved these changes
Awesome, thanks @leesutcliffe

2021-09-30 19:24 UTC, merged