add optional "assignVariable" attribute to "matchSpec"
aquasecurity/tfsec pull request #1338
Opened 2022-01-14 18:47 UTC by gabrielleecredera

- take "name" value and store in map with index "assignVariable" value
- e.g. you can check that an attribute exists, and assign the attribute value to a variable
- variables must start with "TFSEC_VAR_"
- the variable can then be used in any following matchSpec "value" attributes
- added the above to the custom check docs

solves #1337

2022-01-14 18:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/tfsec?pullRequest=1338) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/tfsec?pullRequest=1338) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/tfsec?pullRequest=1338) it.</sub>

2022-01-17 15:39 UTC, gabrielleecredera commented
(not sure how to address the cyclomatic complexity issue, mainly caused by the switch)

2022-01-18 10:31 UTC, owenrumney approved these changes

2022-01-18 17:09 UTC, owenrumney commented
> (not sure how to address the cyclomatic complexity issue, mainly caused by the switch)

I'll take a look at this shortly - thanks for the contribution :+1:

2022-01-19 09:59 UTC, liamg requested changes
Looks good, one minor nitpick

2022-01-19 09:59 UTC, liamg commented on internal/app/tfsec/custom/custom_context.go
> +		variables: make(map[string]string),
Nitpicking but should probably be `make(customCheckVariables)`

2022-01-19 09:59 UTC, liamg commented on internal/app/tfsec/custom/custom_context.go
> +		variables: make(map[string]string),
Nitpicking but should probably be `make(customCheckVariables)`

2022-01-19 10:01 UTC, liamg approved these changes

2022-01-19 10:25 UTC, merged